# Generated by Django 3.2.8 on 2021-10-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
                ('seccion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('rol_usuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id_tienda', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('responsable', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuarios', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('edad', models.IntegerField(null=True)),
                ('genero', models.CharField(max_length=1)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField()),
                ('tipo', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=45)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tienda'),
        ),
    ]
